name: attendx
description: A premium offline-first student attendance management UI built with Flutter.
publish_to: "none"
version: 1.2.0+14

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5
  flutter_displaymode: ^0.7.0
  file_picker: ^8.0.0
  archive: ^3.6.0
  sqflite: ^2.3.3
  path: ^1.9.0
  share_plus: ^12.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
